%script to create Noise_star and the field generated by q+Noise_star
clear
global XP
global YP
flag_loaded_data = 0;

addpath '../matlab';
run('parameters_rla.m')

fprintf('This function creates the scattered field\n\n')

fprintf('Generating the domain from the picture!\n')
len_1=len2;
len_2=len2;
t1=-len_1/2:len_1/(N):len_1/2;t2=-len_2/2:len_2/(N):len_2/2;
[XP,YP]=meshgrid(t1,t2);

% Time to choose the domain
% look into LOCAL_bump
% some domains to try
% domain_type = 11; Gaussian centered at the origin
%		110; four Gaussian bumps
% 		15; Circle with Gaussians
%		18; some lens
%		22; Yu Chen paper example 1
%		23; Yu Chen paper example 2
%		25; Yu Chen paper example 2 smoothed and bounded
%		26; Erf function
%		99; this is special don't play with it
%		101; for pictures. The picture must be processed and turn into a matrix.
%		see test_bomber.m for a bomber and test_submarine.m for a submarine

%doing here the bomber

N = 3;
domain_type = zeros(1,N^2+3);
domain_type(1) = 99;
domain_type(3) = N;

% N \times N matrix of coefficients -> set this to get new training data

% q = \sum_{jk} coefs(j,k) \sin(j (x+\pi/2)) \sin(k(y+\pi/2)) for (x,y) \in
% (-\pi/2,pi/2)^2
coefs = zeros(N);

coefs(1,2) = 1;


domain_type(4:end) = coefs(:).';



%run('test_bomber.m')

fprintf('Generating the data!\n')
for ikh=1:length(khv) %frequency loop
        kh=khv(ikh);
        ipoints=npoints(ikh);
        itheta=ntheta(ikh);
        imodes=nmodes(ikh);
        theta_it=0:2*pi/ntheta(ikh):2*pi-2*pi/ntheta(ikh);
        fprintf('\n************************\n');
        fprintf('************************\n');
        fprintf('\nFor wavenumber kh=%f\n',kh)
        fprintf('\n************************\n');
        fprintf('************************\n');
        %Generating data for the forward problem
        u_sol_aux=data_gen(kh,ipoints,itheta,radius,len2,Np,Ncheb,domain_type);
        u_meas(ikh).field=u_sol_aux.field;
end

fprintf('Finished generating scattered data!\n')

%insert file name here
filename='test_data.mat';

save(filename,'u_meas','ntheta','npoints','radius','khv','-v7.3')

