%script to create Noise_star and the field generated by q+Noise_star
clear
global XP
global YP
flag_loaded_data = 0;

addpath '../matlab';
addpath '../finufft/matlab';
run('parameters_rla_aperture.m')

fprintf('This function creates the scattered field\n\n')

fprintf('Generating the domain from the picture!\n')
len_1=len2;
len_2=len2;
t1=-len_1/2:len_1/(N):len_1/2;t2=-len_2/2:len_2/(N):len_2/2;
[XP,YP]=meshgrid(t1,t2);

% Time to choose the domain
% look into LOCAL_bump
% some domains to try
% domain_type = 11; Gaussian centered at the origin
%		110; four Gaussian bumps
% 		15; Circle with Gaussians
%		18; some lens
%		22; Yu Chen paper example 1
%		23; Yu Chen paper example 2
%		25; Yu Chen paper example 2 smoothed and bounded
%		26; Erf function
%		99; this is special don't play with it
%		101; for pictures. The picture must be processed and turn into a matrix.
%		see test_bomber.m for a bomber and test_submarine.m for a submarine

% coeffs example
N = 2;
domain_type = zeros(1,N^2+3);
domain_type(1) = 99;
domain_type(3) = N;

% N \times N matrix of coefficients -> set this to get new training data

% q = \sum_{jk} coefs(j,k) \sin(j (x+\pi/2)) \sin(k(y+\pi/2)) for (x,y) \in
% (-\pi/2,pi/2)^2
coefs = zeros(N);

coefs(1,1) = 1;

domain_type(4:end) = coefs(:).';



% bomber example
% run('test_bomber.m')

%yuchen
% domain_type(1) = 22;

q_true = LOCAL_bump(XP,YP,domain_type);

fprintf('Generating the data!\n')
%Generating data for the forward problem
u_meas=data_gen_aperture(khv,incdir,sensors,len2,Np,Ncheb,domain_type);
% pause

fprintf('Finished generating scattered data!\n')

%insert file name here
filename='test_data_aperture.mat';

save(filename,'u_meas','domain_type','incdir','sensors','khv','q_true','-v7.3')

